### PR TITLE
Suppress `Object is possibly 'null'`

### LINKED ISSUE #22: Object is possibly 'null'
**Describe the bug**
Under TypeScript with `"strictNullChecks": true` environment (Nuxt.js default configuration), I got the following error and can't compile properly:

```
ERROR in .../node_modules/vue-google-oauth2/index.ts
153:7 Object is possibly 'null'.
    151 |     GoogleAuthConfig = Object.assign(GoogleAuthDefaultConfig, options);
    152 |     if (options.scope) {
  > 153 |       GoogleAuthConfig.scope = options.scope;
        |       ^
    154 |     }
    155 |     if (options.prompt) {
    156 |       prompt = options.prompt;
```

**To Reproduce**
1. Set up Nuxt.js as a TypeScript project.
2. Install this module (v1.4.0) and use it inside the project.
3. Run `npm run generate`.
4. You get the above error.

**Expected behavior**
Properly generate the static website using `npm run generate`.

### PR DESCRIPTION
**Pull request by h-matsuo**
This PR fixes #22, and enables to compile under `"strictNullChecks": true`.

### CODE REVIEW

**Comment by h-matsuo** [comment]
@guruahn Hi! Any problems with this PR?

**Comment by guruahn** [comment]
thanks! @h-matsuo

**Comment by zacharyjallen** [comment]
@guruahn Can we get a release with this fix?

**Comment by guruahn** [comment]
ok!
I just released it!
https://github.com/guruahn/vue-google-oauth2/releases/tag/v1.4.1

**Pull request merged**
