### PR TITLE
add loading auth2 api

### PR DESCRIPTION
**Pull request by wat4dog**
Otherwise, it will report "calling load method of undefined" because gapi.auth2 is not loaded.

### CODE REVIEW

**Comment by xorbis** [comment]
Please merge!

**Comment by wat4dog** [comment]
@xorbis not sure if it's okay to review PR for 2-3 weeks :) hope it will be merged

**Comment by xorbis** [comment]
If you can npm publish, I would gladly install @wat4dog/vue-google-oauth2

**Comment by wat4dog** [comment]
Never did that before :) just tried to help project first time. I will try

**Comment by xorbis** [comment]
Found this: https://www.npmjs.com/package/google-auth-library
It's the official one...

**Comment by wat4dog** [comment]
Initial vue-google-oauth2 is simpliest I found, here is why I pushed PR

**Comment by wat4dog** [comment]
@guruahn sorry, I'd pushed few more changes and published package `vue-google-oauth2-gapi` since I can't wait for merge :) And change to merge is in commit `a1f7eed561cff24f825634a4548caf55cc981cad`

@xorbis https://www.npmjs.com/package/vue-google-oauth2-gapi if you need that right now

**Comment by xorbis** [comment]
Awesome, thanks!

**Comment by guruahn** [comment]
@wat4dog 
sorry, 
All my github notifications gone spam mail box. TT
but I updated to 1.0.10
thanks!!

**Comment by xorbis** [comment]
Works now thanks!

**Pull request closed without merging**
